theme: jekyll-theme-architect
 username               :
  app_id                 :
  publisher              :
og_image                 :  # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
# Analytics
analytics:
  provider               :  "google-universal" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          :
# Site Author
author:
  name             : "Ashraf Rizvi"
  avatar           : "profile.png"
  bio              : "Undergrad Student"
  location         : "Mirpur DOHS"
  employer         :
#  pubmed           : "https://www.ncbi.nlm.nih.gov/pubmed/?term=john+snow"
